# Generated by Django 3.1.6 on 2021-03-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='desc',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
    ]
