# Generated by Django 3.1.6 on 2021-03-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0002_shows_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
