# Generated by Django 3.1.6 on 2021-03-13 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20210312_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='course_desc',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='courses',
            name='desc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses_app.description'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_comments', to='courses_app.courses')),
            ],
        ),
    ]
